# Generated by Django 4.0 on 2022-01-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default='sam', max_length=256),
        ),
    ]
