# Generated by Django 4.0 on 2022-01-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_doctor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_no',
            field=models.CharField(default='2RT5HAc56T', max_length=12),
        ),
        migrations.AddField(
            model_name='other',
            name='username',
            field=models.CharField(default='sam', max_length=256),
        ),
    ]
