# Generated by Django 4.0 on 2022-01-23 05:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_doctor_license_no_other_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+917838124712', max_length=128, region=None, unique=True),
        ),
    ]
